from typing import TypeAlias

from lokit.data.structure import Data

NativeRecord: TypeAlias = tuple[
    bool,
    str,
    str,
    str | None,
    list[tuple[str, str]],
    str,
    dict[str, str],
    bytes | None,
]
LokitRecord: TypeAlias = tuple[str, Data]

class Reader:
    def __init__(
        self,
        path: str,
        format_name: str,
        source_language: str | None = ...,
        target_language: str | None = ...,
        mode: str = ...,
    ) -> None: ...
    @property
    def version(self) -> str: ...
    @property
    def source_locale(self) -> str | None: ...
    @property
    def target_locale(self) -> str | None: ...
    @property
    def source_language(self) -> str | None: ...
    @property
    def target_language(self) -> str | None: ...
    @property
    def target_locales(self) -> list[str]: ...
    @property
    def target_languages(self) -> list[str]: ...
    @property
    def export_origin(self) -> str: ...
    @property
    def export_timestamp(self) -> str: ...
    @property
    def extensions(self) -> dict[str, str]: ...
    @property
    def closed(self) -> bool: ...
    def read_batch(self, batch_size: int = ...) -> list[NativeRecord]: ...
    def close(self) -> None: ...

class LokitReader:
    def __init__(self, path: str) -> None: ...
    @property
    def source_locale(self) -> str: ...
    @property
    def target_locale(self) -> str | None: ...
    @property
    def target_locales(self) -> list[str]: ...
    @property
    def format_version(self) -> str: ...
    @property
    def export_origin(self) -> str: ...
    @property
    def export_timestamp(self) -> str: ...
    @property
    def source_language(self) -> str | None: ...
    @property
    def target_language(self) -> str | None: ...
    @property
    def target_languages(self) -> list[str]: ...
    @property
    def extensions(self) -> dict[str, str]: ...
    @property
    def closed(self) -> bool: ...
    def read_batch(self, batch_size: int = ...) -> list[LokitRecord]: ...
    def close(self) -> None: ...

class LokitWriter:
    def __init__(
        self,
        path: str,
        source_locale: str,
        target_locale: str | None,
        target_locales: tuple[str, ...],
        format_version: str,
        export_origin: str,
        export_timestamp: str,
        source_language: str | None,
        target_language: str | None,
        target_languages: tuple[str, ...],
        extensions: dict[str, str],
    ) -> None: ...
    @property
    def closed(self) -> bool: ...
    def write(self, unit_id: str, data: Data) -> None: ...
    def close(self) -> None: ...
    def abort(self) -> None: ...

def backend_version() -> str: ...
