from typing import TypeAlias

NativeRecord: TypeAlias = tuple[
    bool,
    str,
    str,
    str | None,
    list[tuple[str, str]],
    str,
    dict[str, str],
    bytes | None,
]

class Reader:
    def __init__(
        self,
        path: str,
        format_name: str,
        source_language: str | None = ...,
        target_language: str | None = ...,
        mode: str = ...,
    ) -> None: ...
    @property
    def version(self) -> str: ...
    @property
    def source_locale(self) -> str | None: ...
    @property
    def target_locale(self) -> str | None: ...
    @property
    def source_language(self) -> str | None: ...
    @property
    def target_language(self) -> str | None: ...
    @property
    def target_locales(self) -> list[str]: ...
    @property
    def target_languages(self) -> list[str]: ...
    @property
    def export_origin(self) -> str: ...
    @property
    def export_timestamp(self) -> str: ...
    @property
    def extensions(self) -> dict[str, str]: ...
    @property
    def closed(self) -> bool: ...
    def read_batch(self, batch_size: int = ...) -> list[NativeRecord]: ...
    def close(self) -> None: ...

def backend_version() -> str: ...
