"""Stable public data types used by Lokit's typed APIs."""

from lokit.data.structure import (
    AdjacentContext,
    BaseStructure,
    Comment,
    ConversionStats,
    Data,
    Meta,
    Origin,
    Plural,
    PluralCategory,
    StreamingStructure,
    TargetData,
    TranslationStatus,
)
from lokit.types.content import (
    ConversionDiagnostic,
    ConversionOutcome,
    ConversionReport,
    InlineCode,
    InlineCodeKind,
    InlineSemantic,
    NativeCode,
    Segment,
    TagAttribute,
    TagIntegrityError,
    TagSyntax,
    UnsupportedTagPolicy,
    iter_rendered,
    legacy_parts_match_text,
    render_segment,
    segment_from_legacy,
)

__all__ = [
    "AdjacentContext",
    "BaseStructure",
    "Comment",
    "ConversionDiagnostic",
    "ConversionOutcome",
    "ConversionReport",
    "ConversionStats",
    "Data",
    "InlineCode",
    "InlineCodeKind",
    "InlineSemantic",
    "Meta",
    "NativeCode",
    "Origin",
    "Plural",
    "PluralCategory",
    "Segment",
    "StreamingStructure",
    "TagAttribute",
    "TagIntegrityError",
    "TagSyntax",
    "TargetData",
    "TranslationStatus",
    "UnsupportedTagPolicy",
    "iter_rendered",
    "legacy_parts_match_text",
    "render_segment",
    "segment_from_legacy",
]
