"""Stable public data types used by Lokit's typed APIs."""

from lokit.data.interchange_types import DEFAULT_DICT_FIELDS, DictField, StringMode, TranslationRow
from lokit.data.structure import (
    AdjacentContext,
    BaseStructure,
    CodePart,
    Comment,
    ConversionStats,
    Data,
    Meta,
    Origin,
    Plural,
    PluralCategory,
    StreamingStructure,
    Tags,
    TargetData,
    TargetTags,
    TextPart,
    TranslationStatus,
)
from lokit.data.tag_types import TieData, TieType
from lokit.data.targets import StreamingTargetSplit
from lokit.placeholders import (
    CanonicalPlaceholderText,
    PlaceholderOccurrence,
    PlaceholderProjection,
    PlaceholderRole,
    PlaceholderSyntax,
    PlaceholderValueType,
    ReformedTarget,
)
from lokit.types.content import (
    ConversionDiagnostic,
    ConversionOutcome,
    ConversionReport,
    InlineCode,
    InlineCodeKind,
    InlineSemantic,
    NativeCode,
    Segment,
    TagAttribute,
    TagIntegrityError,
    TagSyntax,
    UnsupportedTagPolicy,
    iter_rendered,
    legacy_parts_match_text,
    render_segment,
    segment_from_legacy,
)
from lokit.types.match import MatchResult

__all__ = [
    "DEFAULT_DICT_FIELDS",
    "AdjacentContext",
    "BaseStructure",
    "CanonicalPlaceholderText",
    "CodePart",
    "Comment",
    "ConversionDiagnostic",
    "ConversionOutcome",
    "ConversionReport",
    "ConversionStats",
    "Data",
    "DictField",
    "InlineCode",
    "InlineCodeKind",
    "InlineSemantic",
    "MatchResult",
    "Meta",
    "NativeCode",
    "Origin",
    "PlaceholderOccurrence",
    "PlaceholderProjection",
    "PlaceholderRole",
    "PlaceholderSyntax",
    "PlaceholderValueType",
    "Plural",
    "PluralCategory",
    "ReformedTarget",
    "Segment",
    "StreamingStructure",
    "StreamingTargetSplit",
    "StringMode",
    "TagAttribute",
    "TagIntegrityError",
    "TagSyntax",
    "Tags",
    "TargetData",
    "TargetTags",
    "TextPart",
    "TieData",
    "TieType",
    "TranslationRow",
    "TranslationStatus",
    "UnsupportedTagPolicy",
    "iter_rendered",
    "legacy_parts_match_text",
    "render_segment",
    "segment_from_legacy",
]
